
#include <stdexcept>
namespace ErrorHandling {
	void demo() {

	}


	void throwAnException() {
		throw std::out_of_range("Out of it");
	}
}
